In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset[['Purchased']].value_counts()

Purchased
0            257
1            143
Name: count, dtype: int64

In [5]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [6]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [7]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent = dataset[['User ID', 'Age', 'EstimatedSalary','Gender_Male']]

In [9]:
dependent = dataset[['Purchased']]

In [10]:
#Split train and test sets using sklearn
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
X_train

      User ID  Age  EstimatedSalary  Gender_Male
92   15809823   26            15000            1
223  15593715   60           102000            1
234  15619407   38           112000            0
232  15813113   40           107000            1
377  15800215   42            53000            0
..        ...  ...              ...          ...
323  15619465   48            30000            0
192  15779581   29            43000            1
117  15591433   36            52000            1
47   15776348   27            54000            0
172  15794661   26           118000            0

[280 rows x 4 columns]

In [12]:
#standardisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # mean and standard deviation calculate here
X_test = sc.transform(X_test)

In [13]:
X_train

array([[ 1.67118864, -1.1631724 , -1.5849703 ,  0.99288247],
       [-1.38839503,  2.17018137,  0.93098672,  0.99288247],
       [-1.02465642,  0.0133054 ,  1.22017719, -1.00716855],
       ...,
       [-1.42070282, -0.18277423, -0.51496559,  0.99288247],
       [ 1.19726096, -1.06513258, -0.45712749, -1.00716855],
       [ 1.45653019, -1.1631724 ,  1.39369146, -1.00716855]])

In [15]:
#Model creation #learning process 
#procedure
from sklearn.svm import SVC
# to sggregate a model in SVM using straight line when kernel ="linear"
#rbf for non linear # radial bais function
classifier = SVC(kernel="rbf", C=1000)
classifier.fit(X_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1000)

In [16]:
classifier.intercept_

array([-2.37088562])

In [17]:
# to knoe how many suppot vector does the model take
classifier.n_support_

array([37, 33])

In [18]:
# the model is created with 34 datapoints
classifier.support_

array([  2,  17,  37,  45,  50,  61,  75,  76,  77,  93,  94, 101, 104,
       118, 122, 133, 135, 138, 144, 158, 165, 167, 180, 191, 192, 194,
       198, 208, 210, 212, 219, 221, 231, 232, 233, 242, 263,   6,   8,
        13,  19,  25,  26,  32,  34,  48,  51,  65,  68,  71,  72,  79,
        83,  86,  89, 106, 110, 115, 125, 136, 150, 151, 177, 204, 216,
       235, 241, 260, 268, 269])

In [21]:
y_predict = classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)

In [23]:
print(cm)

[[72  7]
 [12 29]]

In [24]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_predict)

In [25]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.86      0.91      0.88        79
           1       0.81      0.71      0.75        41

    accuracy                           0.84       120
   macro avg       0.83      0.81      0.82       120
weighted avg       0.84      0.84      0.84       120